# Etapa 1 — Build
FROM node:18 AS build
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Etapa 2 — Servir con NGINX en Render
FROM nginx:stable-alpine

# Copiar build
COPY --from=build /app/dist /usr/share/nginx/html

# Copiar configuración personalizada
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Render usa este puerto
ENV PORT 10000
EXPOSE 10000

CMD ["nginx", "-g", "daemon off;"]
